import type { Business, Review } from "./types";

export const businesses: Business[] = [
  {
    id: "karim-jama-masjid",
    name: "Karim's Jama Masjid",
    category: "Restaurants",
    location: "Old Delhi",
    shortDescription: "Famous Delhi delicacies and traditional cuisine",
    addressLine: "Jama Masjid, Old Delhi",
    averageRating: 4.7,
    ratingCount: 156,
    averageBreakdown: { quality: 4.8, service: 4.6, value: 4.5 },
  },
  {
    id: "indian-coffee-house",
    name: "Indian Coffee House",
    category: "Cafes",
    location: "Connaught Place",
    shortDescription: "Historic coffee house with Indian charm",
    addressLine: "Connaught Place, New Delhi",
    averageRating: 4.4,
    ratingCount: 98,
    averageBreakdown: { quality: 4.5, service: 4.3, value: 4.2 },
  },
  {
    id: "looks-salon",
    name: "Looks Salon",
    category: "Salons & Spas",
    location: "Rajouri Garden",
    shortDescription: "Premium salon and spa services",
    addressLine: "Rajouri Garden, West Delhi",
    averageRating: 4.6,
    ratingCount: 87,
    averageBreakdown: { quality: 4.7, service: 4.5, value: 4.4 },
  },
  {
    id: "reliance-smart",
    name: "Reliance Smart",
    category: "Grocery Stores",
    location: "Dwarka",
    shortDescription: "Quality grocery and household items",
    addressLine: "Dwarka, South West Delhi",
    averageRating: 4.3,
    ratingCount: 142,
    averageBreakdown: { quality: 4.4, service: 4.2, value: 4.1 },
  },
  {
    id: "quickfix-electronics",
    name: "QuickFix Electronics",
    category: "Repair Services",
    location: "Lajpat Nagar",
    shortDescription: "Fast and reliable electronics repair",
    addressLine: "Lajpat Nagar, South Delhi",
    averageRating: 4.5,
    ratingCount: 73,
    averageBreakdown: { quality: 4.6, service: 4.4, value: 4.3 },
  },
  {
    id: "cult-fit-gym",
    name: "Cult Fit Gym",
    category: "Gyms & Fitness",
    location: "Saket",
    shortDescription: "Modern fitness center with expert trainers",
    addressLine: "Saket, South Delhi",
    averageRating: 4.4,
    ratingCount: 205,
    averageBreakdown: { quality: 4.5, service: 4.3, value: 4.2 },
  },
  {
    id: "apollo-clinic",
    name: "Apollo Clinic",
    category: "Clinics & Pharmacies",
    location: "Karol Bagh",
    shortDescription: "Trusted healthcare and medical services",
    addressLine: "Karol Bagh, Delhi",
    averageRating: 4.6,
    ratingCount: 128,
    averageBreakdown: { quality: 4.7, service: 4.5, value: 4.4 },
  },
  {
    id: "gupta-general-store",
    name: "Gupta General Store",
    category: "Local Shops",
    location: "Janakpuri",
    shortDescription: "Your neighborhood shopping destination",
    addressLine: "Janakpuri, West Delhi",
    averageRating: 4.2,
    ratingCount: 64,
    averageBreakdown: { quality: 4.3, service: 4.1, value: 4.0 },
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    businessId: "karim-jama-masjid",
    authorName: "Rajesh",
    createdAtISO: "2026-02-12T10:12:00.000Z",
    ratings: { quality: 5, service: 4, value: 5 },
    overall: 4.7,
    title: "Authentic Delhi food",
    body: "Must try traditional biryani. The taste is authentic and portions are generous.",
  },
  {
    id: "r2",
    businessId: "indian-coffee-house",
    authorName: "Priya",
    createdAtISO: "2026-01-28T16:40:00.000Z",
    ratings: { quality: 4, service: 4, value: 4 },
    overall: 4.2,
    title: "Iconic Delhi landmark",
    body: "Great atmosphere and good coffee. A bit crowded but worth the visit.",
  },
  {
    id: "r3",
    businessId: "looks-salon",
    authorName: "Anjali",
    createdAtISO: "2026-02-02T19:05:00.000Z",
    ratings: { quality: 5, service: 5, value: 4 },
    overall: 4.8,
    title: "Best salon experience",
    body: "Professional staff and high-quality treatments. Definitely coming back!",
  },
  {
    id: "r4",
    businessId: "cult-fit-gym",
    authorName: "Amit",
    createdAtISO: "2026-03-01T01:15:00.000Z",
    ratings: { quality: 4, service: 4, value: 4 },
    overall: 4.2,
    title: "Great fitness experience",
    body: "Modern equipment and knowledgeable trainers. Membership is worth it.",
  },
  {
    id: "r5",
    businessId: "reliance-smart",
    authorName: "Neha",
    createdAtISO: "2026-02-20T08:22:00.000Z",
    ratings: { quality: 5, service: 4, value: 4 },
    overall: 4.4,
    title: "Convenient shopping",
    body: "Wide variety of products and clean store. Good prices on essentials.",
  },
  {
    id: "r6",
    businessId: "quickfix-electronics",
    authorName: "Vikram",
    createdAtISO: "2026-01-10T14:00:00.000Z",
    ratings: { quality: 4, service: 4, value: 4 },
    overall: 4.4,
    title: "Fast and reliable",
    body: "Got my phone fixed quickly. The technician knew what they were doing.",
  },
  {
    id: "r7",
    businessId: "apollo-clinic",
    authorName: "Dr. Sharma",
    createdAtISO: "2026-02-26T17:33:00.000Z",
    ratings: { quality: 5, service: 5, value: 4 },
    overall: 4.7,
    title: "Excellent medical care",
    body: "Professional doctors and clean facilities. Very satisfied with the treatment.",
  },
];

export function getReviewsForBusiness(businessId: string): Review[] {
  return reviews
    .filter((r) => r.businessId === businessId)
    .slice()
    .sort((a, b) => b.createdAtISO.localeCompare(a.createdAtISO));
}

